import { Suspense } from 'react';
import Footer from './Footer';
import Header from './Header';
import './globals.css';
import type { Metadata } from 'next';
import Loading from './loadind';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="container mx-auto bg-slate-700 text-slate-50">
        <div className="flex flex-col min-h-screen">
          <Header />
          <main className="flex-grow">
            {/* @see https://react.dev/reference/react/Suspense */}
            {/* Suspense: childrenが読み込みを完了するまでfallbackを表示する。 */}
            <Suspense fallback={<Loading />}>{children}</Suspense>
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
